#!/usr/bin/env bash

if
  [[ -s "/home/ivar/.rvm/gems/ruby-2.7.1/environment" ]]
then
  source "/home/ivar/.rvm/gems/ruby-2.7.1/environment"
  exec y2racc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ivar/.rvm/gems/ruby-2.7.1/environment'" >&2
  exit 1
fi
